services:
  spritesheet-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spritesheet-generator
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spritesheet-generator.rule=Host(`spritesheet.localhost`)"
      - "traefik.http.services.spritesheet-generator.loadbalancer.server.port=80"